#!/bin/bash

NSCREENS="$(xrandr | grep --count [^dis]connected)"
if [ "$NSCREENS" == "1" ]; then
    xrandr --auto
else
    if [ "$(xrandr | grep --count 'LVDS1 connected')" == "1" ] ;then
        SCREEN="LVDS1"
    else
        SCREEN="eDP1"
    fi
    xrandr --output HDMI1 --auto --dpi 92 --output $SCREEN --auto --left-of HDMI1
fi
