#!/bin/bash

# requires:
# gtk-lunch
# wmctrl
# telegram in .local/share/applications/telegramdesktop.desktop

TELEPID=$(ps -e | egrep "(telegram$|telegram-desktop$|telegram-deskto$)" | awk '{print $1}')

# Check if telegram is running
if [ ! -z "$TELEPID" ]
then
    TELELINE=$(wmctrl -l -p | grep "$TELEPID")
    TELEWS=$(echo "$TELELINE" | awk '{print $2}')
    #TELEWID=$(echo "$TELELINE" | awk '{print $1}')

    # close telegram
    #wmctrl -i -c "$TELEWID"
    kill -9 "$TELEPID"

    # relaunch telegram
    #cd .local/share/applications/
    gtk-launch telegramdesktop.desktop
    #cd -

    TELEPID=$(ps -e | egrep "(telegram$|telegram-desktop$|telegram-deskto$)" | awk '{print $1}')
    TELELINE=$(wmctrl -l -p | grep "$TELEPID")
    # wait for it to be recognized by wmctrl
    while [ -z "$TELELINE" ]
    do
        sleep 0.05
        TELELINE=$(wmctrl -l -p | grep "$TELEPID")
    done

    TELEWID=$(echo "$TELELINE" | awk '{print $1}')
    wmctrl -i -r "$TELEWID" -t "$TELEWS"
fi
