#!/bin/bash

if [ "$(pacmd list-cards | grep "active profile:" | grep hdmi)" ]; then
    pacmd set-card-profile 0 output:analog-stereo+input:analog-stereo
else
    pacmd set-card-profile 0 output:hdmi-stereo+input:analog-stereo
fi
